/**
 * Auth Constants
 *
 * Constants used across auth modules. Separated from audit.ts to allow
 * client components to import without pulling in server-side code.
 *
 * Note: Some types are duplicated from Prisma schema to avoid importing
 * @prisma/client in client components.
 */

/**
 * User type enum values (mirrors Prisma AuthUserType enum).
 * Used in client components to avoid importing @prisma/client.
 */
export const AUTH_USER_TYPES = {
  MEMBER_COMPANY_ADMIN: 'MEMBER_COMPANY_ADMIN',
  MEMBER_COMPANY_USER: 'MEMBER_COMPANY_USER',
  RANZ_ADMIN: 'RANZ_ADMIN',
  RANZ_STAFF: 'RANZ_STAFF',
  RANZ_INSPECTOR: 'RANZ_INSPECTOR',
  EXTERNAL_INSPECTOR: 'EXTERNAL_INSPECTOR',
} as const;

/** Type for AUTH_USER_TYPES values */
export type AuthUserTypeValue = (typeof AUTH_USER_TYPES)[keyof typeof AUTH_USER_TYPES];

/**
 * Standard authentication action types.
 * Use these constants for consistency across the codebase.
 */
export const AUTH_ACTIONS = {
  // Login actions
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_RATE_LIMITED: 'LOGIN_RATE_LIMITED',
  LOGIN_ERROR: 'LOGIN_ERROR',

  // Logout actions
  LOGOUT: 'LOGOUT',
  LOGOUT_ALL_SESSIONS: 'LOGOUT_ALL_SESSIONS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',

  // Password actions
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  FIRST_LOGIN_PASSWORD_CHANGE: 'FIRST_LOGIN_PASSWORD_CHANGE',

  // Account actions
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  WELCOME_EMAIL_SENT: 'WELCOME_EMAIL_SENT',
  WELCOME_EMAIL_RESENT: 'WELCOME_EMAIL_RESENT',
  ACCOUNT_ACTIVATED: 'ACCOUNT_ACTIVATED',
  ACCOUNT_ACTIVATION_EXPIRED: 'ACCOUNT_ACTIVATION_EXPIRED',

  // User management actions (admin operations)
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_REACTIVATED: 'USER_REACTIVATED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_COMPANY_CHANGED: 'USER_COMPANY_CHANGED',
  USER_BATCH_UPDATED: 'USER_BATCH_UPDATED',
  PASSWORD_ADMIN_RESET: 'PASSWORD_ADMIN_RESET',

  // Security actions (SECR-07)
  SUSPICIOUS_LOGIN_DETECTED: 'SUSPICIOUS_LOGIN_DETECTED',

  // Migration actions (Phase 6)
  MIGRATION_USER_TO_CUSTOM: 'MIGRATION_USER_TO_CUSTOM',
  MIGRATION_COHORT_COMPLETE: 'MIGRATION_COHORT_COMPLETE',
  MIGRATION_ROLLBACK: 'MIGRATION_ROLLBACK',
  MIGRATION_ROLLBACK_LATE: 'MIGRATION_ROLLBACK_LATE',
  MIGRATION_ROLLBACK_BATCH: 'MIGRATION_ROLLBACK_BATCH',
  MIGRATION_IMPORT_SINGLE: 'MIGRATION_IMPORT_SINGLE',
  MIGRATION_IMPORT_BATCH: 'MIGRATION_IMPORT_BATCH',
  MIGRATION_IMPORT_ALL: 'MIGRATION_IMPORT_ALL',
} as const;

/** Type for AUTH_ACTIONS values */
export type AuthAction = (typeof AUTH_ACTIONS)[keyof typeof AUTH_ACTIONS];
